'use strict';
const scenarios=[
 ['Fresh start','A clear composer and compact identity; no empty editor pane.'],
 ['Idle populated workspace','Files, editor and conversation share one set of boundaries.'],
 ['Simple conversation','The answer is the strongest durable content.'],
 ['Prompt just submitted','T+0: request is durable; composer is ready under existing queue semantics.'],
 ['Thinking','One live state; no invented percent or empty reasoning block.'],
 ['Plan active','Active step is primary. Completed steps recede.'],
 ['Tool running','Exact command, running state and existing session identity.'],
 ['Multiple tools grouped','Contiguous exploration is compact; Ctrl+O exposes exact activity.'],
 ['Long-running investigation','One stable active row; elapsed time is not a progress estimate.'],
 ['Approval','Existing inline approval: command, reason, cwd, choices; one keyboard owner.'],
 ['Error','Exit status remains visible without relying on color or final prose.'],
 ['Recovery','Earlier failure remains truthful; later success does not rewrite it.'],
 ['Cancellation','Turn stopped; process termination is not inferred.'],
 ['Final response streaming','The answer grows in place; live state remains until actual completion.'],
 ['Completed turn','Final answer dominates; plan/activity metadata compresses.'],
 ['Historical collapsed turn','Exact request and final answer remain; intermediate detail recedes.'],
 ['Historical expanded turn','Existing Ctrl+O detail mode reveals retained narration, calls and results.'],
 ['Long conversation','Repeated request/answer rhythm supports scanning.'],
 ['Editor NORMAL','File identity above; mode and position below.'],
 ['Editor INSERT','Same geometry; mode and owned caret change.'],
 ['Editor dirty','Unsaved marker is separate from Git modification state.'],
 ['Terminal focused','One top rule; shell content retains its own rendering.'],
 ['Files search','A one-row field; pointer and owner are visibly distinct.'],
 ['Model picker','Preserve model, provider, source/account and active route details.'],
 ['Theme picker','Existing bottom dock and preview, using the shared component grammar.'],
 ['Review Changes','Diff retains both line numbers, hunks, file list and existing review controls.'],
 ['Save / Discard / Cancel','Content-sized dialog; existing actions and bindings only.'],
 ['Narrow layout','80×24; Files hidden under the existing width gate.'],
 ['Standard layout','120×35; chat remains readable with a file open.'],
 ['Wide layout','160×45; more code width, bounded prose measure.']
];
let state=Number(new URLSearchParams(location.search).get('state')||1)-1;
state=Math.max(0,Math.min(29,state));let cols=120,rows=35,expanded=false,owner='Composer',overlay='',modalChoice=0,search='formatter',historyOffset=0;
const terminal=document.querySelector('#terminal'),selector=document.querySelector('#scenario');
scenarios.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${String(i+1).padStart(2,'0')} · ${s[0]}`;selector.append(o)});
let grid; const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function put(x,y,text,role='primary',surface=''){if(y<0||y>=rows)return;Array.from(text).forEach((ch,i)=>{if(x+i>=0&&x+i<cols)grid[y][x+i]={ch,cl:[role,surface].filter(Boolean).join(' ')}})}
function fill(x,y,w,h,surface='panel'){for(let r=y;r<Math.min(rows,y+h);r++)put(x,r,' '.repeat(Math.max(0,w)),'primary',surface)}
function rule(x,y,w,role='border'){put(x,y,'─'.repeat(Math.max(0,w)),role)}
function textLines(text,w){let out=[];for(const line of text.split('\n')){let rest=line;while(rest.length>w){let at=rest.lastIndexOf(' ',w);if(at<w*.3)at=w;out.push(rest.slice(0,at));rest=rest.slice(at).trimStart()}out.push(rest)}return out}
function line(text,role='primary',gap=0){return {text,role,gap}}
function title(x,y,w,label,focused=false){rule(x,y,w);put(x,y,`${focused?'>':' '} ${label} `,focused?'focus':'secondary')}
function box(x,y,w,h,label){fill(x,y,w,h);put(x,y,'┌'+'─'.repeat(w-2)+'┐','border','panel');for(let i=1;i<h-1;i++){put(x,y+i,'│','border','panel');put(x+w-1,y+i,'│','border','panel')}put(x,y+h-1,'└'+'─'.repeat(w-2)+'┘','border','panel');put(x+2,y,`> ${label} `,'focus','panel')}
function frame(){grid=Array.from({length:rows},()=>Array.from({length:cols},()=>({ch:' ',cl:'primary'})));fill(0,0,cols,1,'root');put(1,0,'Forge  ·  astra-fixture  /  fix/ux-fixture','secondary','root');put(Math.max(45,cols-18),0,'0.1.0-beta.8','muted','root');}
function activity(detail){let a=[line('[x] Explored repository · 3 reads · 2 searches','secondary')];if(detail)a.push(line('    Read   formatter.py · 3 lines','secondary'),line('    Read   test_formatter.py · 15 lines','secondary'),line('    Read   README.md · 3 lines','secondary'),line('    Search "display_name" · 5 matches','secondary'),line('    Search "unittest" · 2 matches','secondary'));return a}
function plan(active=1,detail=false){let labels=['Inspect formatter and call sites','Edit formatter and add regression tests','Run unittest verification'];let a=[line(`Plan · ${active}/3 complete`,'secondary')];labels.forEach((s,i)=>{a.push(line(`${i<active?'[x]':i===active?'[>]':'[ ]'} ${s}`,i===active?'heading':'secondary'));if(detail&&i<active)a.push(line('    '+(i===0?'Read formatter.py, test_formatter.py':'Edit formatter.py, test_formatter.py'),'muted'))});return a}
function finalAnswer(){return [line('Forge','heading'),line('Name formatting now trims surrounding spaces and omits empty name parts.','primary',1),line('Changes','heading'),line('formatter.py','info'),line('test_formatter.py','info'),line('Added blank-first, blank-last and whitespace cases.','primary',1),line('Verification','heading'),line('[x] python3 -m unittest -v · exit 0','success'),line('4 tests passed.','primary'),line('No broader test suite was run.','secondary',1)]}
function transcript(){const s=state+1;const detail=expanded||s===17;let a=[];
 if(s===1)return [line('Forge','heading'),line('OpenAI · ChatGPT / gpt-5.6-luna','secondary'),line('24 skills loaded','secondary',1),line('Describe a task to begin.','primary'),line('Explain this project · Find a bug · Write tests','muted')];
 const req=s===3?'Summarize this repository.':s===9?'Investigate architecture and performance hotspots.':s===10?'Read the harmless approval fixture.':s===11||s===12?'Run an intentional failure, then verify recovery.':s===13?'Run the long command.': 'Trim name parts and add regression tests.';
 a.push(line('| You','secondary'),line('| '+req,'primary',1));
 if(s===4)return a;
 if(s===5)return a.concat(line('I’ll inspect the formatter and its tests.','secondary'));
 if(s===3)return a.concat(activity(false),line('','primary'),line('Forge','heading'),line('Forge is a Rust terminal coding-agent workspace. Its TUI combines conversation, files, editing, diffs and a shell.','primary'),line('The agent loop, providers, tools and durable sessions live in separate crates.','primary',1),line('Finished · 39 tools · 1m 04s','muted'));
 if(s===6)return a.concat(plan(1,detail),line('','primary'),activity(detail));
 if(s===7)return a.concat(plan(2,false),line('','primary'),line('[>] Shell  python3 -m unittest -v','primary'),line('    session #1 · running','secondary'),line('    test_full_name ... ok','secondary'));
 if(s===8||s===9)return a.concat(plan(1,false),line('','primary'),activity(detail),line('','primary'),line('The formatter joins raw values without trimming.','secondary'),line('[>] Read   test_formatter.py','primary'),line('    Inspecting existing edge-case coverage','secondary'));
 if(s===10)return a.concat(line('[|] Approval needed','warning'),line('Forge wants to run a shell command.','primary'),line('$ cat /tmp/astra-forge-approval-note.txt','primary'),line('cwd /private/tmp/astra-forge-fixture','secondary'),line('Reason: sandbox denied access outside the workspace.','primary',1),line('> y Run once','focus'),line('    Runs now. You will be asked again.','secondary'),line('  n Don’t run','primary'),line('    The agent is told the command was denied.','secondary'),line('  N Don’t run, and say why','primary'),line('    Type a line for the agent.','secondary'),line('↑↓ move · Enter confirm · Esc don’t run','secondary'));
 if(s===11||s===12){a.push(line('[!] Shell  python3 -c "raise SystemExit(1)"','error'),line('    exit 1 · no output','secondary'));if(s===12)a.push(line('[x] Shell  printf RECOVERED','success'),line('    exit 0 · RECOVERED','secondary'),line('','primary'),line('Forge','heading'),line('The intentional failure exited 1. The next command exited 0 and printed RECOVERED.','primary'),line('Finished · 2 tools · 12s','muted'));return a}
 if(s===13)return a.concat(line('[-] Turn cancelled','secondary'),line('    python3 -c "import time; time.sleep(180)"','primary'),line('    Last reported process state: running.','secondary'),line('    Process termination is not confirmed.','warning'));
 if(s===14)return a.concat(activity(false),line('','primary'),line('Forge','heading'),line('Name formatting now trims surrounding spaces and omits empty name parts.','primary'),line('','primary'),line('Verification','heading'),line('The requested test suite','primary'));
 if(s===18){let hist=[];for(let i=0;i<3;i++)hist.push(line('| You','secondary'),line('| '+['Summarize this repository.','Trim name parts and add tests.','Run failure and recovery.'][i],'primary'),line('[x] Activity · '+[6,10,2][i]+' tools · Ctrl+O details','secondary'),line('Forge','heading'),line(['Rust workspace with a terminal UI, agent loop, providers and tools.','Formatter updated; four unittest cases passed.','Intentional exit 1 retained; subsequent printf exited 0.'][i],'primary'),line('Finished · '+[28,44,12][i]+'s','muted',1));return hist}
 if(detail)a.push(line('Activity · expanded · Ctrl+O collapse','secondary'),line('Narration: I’ll inspect, edit and verify the formatter.','secondary'),...activity(true),...plan(3,true),line('[x] Edit   formatter.py · test_formatter.py','secondary'),line('[x] Shell  python3 -m unittest -v · exit 0','secondary'),line('    Ran 4 tests in 0.001s · OK','secondary'),line('','primary'));
 else a.push(line('[x] Activity · 10 tools · Plan 3/3 · Ctrl+O details','secondary',1));
 a.push(...finalAnswer(),line('Finished · 10 tools · 44s','muted'));return a;
}
function render(){frame();const s=state+1;const modal=overlay||(s===24?'model':s===25?'theme':s===27?'save':'');const editing=[2,19,20,21,26,28,29,30].includes(s);const term=s===22;const files=cols>=116?(cols>=200?28:cols>=160?24:22):0;const bodyY=2;const bodyH=rows-3;const terminalH=term?Math.min(12,Math.floor(bodyH*.35)):0;const bottom=rows-2-terminalH;const remaining=cols-2-files-(files?1:0)-(editing?1:0);const chatW=editing?Math.min(88,Math.max(44,Math.round(remaining*.55))):remaining;const workW=editing?remaining-chatW:0;let chatX=1+files+(files?1:0)+workW+(editing?1:0);const actualOwner=modal?'Modal':s===10?'Approval':owner;put(1,1,'1 astra-fixture · fix/ux-fixture','secondary');
 if(files){title(1,bodyY,files,'Files',actualOwner==='Files');fill(2,bodyY+1,files-2,1);put(2,bodyY+1,(s===23?'> '+search:'  Search files…').slice(0,files-2),actualOwner==='Search'?'focus':'muted','panel');let entries=s===26?['M formatter.py','M test_formatter.py']:s===23?(search.includes('zzz')?['No files match.']:['> formatter.py  M','  test_formatter.py  M']):['v astra-fixture','  formatter.py  M','  README.md','  test_formatter.py M','> .forge'];entries.forEach((v,i)=>put(2,bodyY+3+i,v.slice(0,files-2),i===1?'primary':'secondary',i===1?'selected':''));for(let y=bodyY;y<=bottom;y++)put(files+1,y,'│','border')}
 if(editing){const x=files?files+2:1;title(x,bodyY,workW,s===26?'Review Changes':'formatter.py'+(s===21?' *':''),actualOwner==='Editor');const code=s===26?['    formatter.py  +1 -1','@@ -1,2 +1,2 @@','1 1 def display_name(first, last):','2   - return first + " " + last','  2 + return " ".join(','  3 +   p.strip() for p in (first, last)','  4 +   if p.strip())']:['1 def display_name(first, last):','2     return " ".join(','3         part.strip()','4         for part in (first, last)','5         if part.strip()','6     )'];let y=bodyY+2;code.forEach(v=>{let role=v.includes('+')?'success':v.includes('- return')?'error':v.includes('@@')?'info':'primary';textLines(v,workW-2).forEach(l=>put(x+1,y++,l,role))});if([19,20,21].includes(s)&&actualOwner==='Editor')put(x+3,bodyY+2,'d','caret');fill(x,bottom,workW,1);put(x+1,bottom,(s===26?'n/p file · ]/[ hunk':`${s===20?'INSERT':'NORMAL'}  ${s===21?'* modified · ':''}1:1 · python`).slice(0,workW-2),'secondary','panel');for(let y=bodyY;y<=bottom;y++)put(x+workW,y,'│','border')}
 title(chatX,bodyY,chatW,'Conversation',actualOwner==='Conversation');const live=[4,5,6,7,8,9,11,14].includes(s);const inputH=1;const compY=bottom-inputH;const liveY=compY-1;let maxY=live?liveY-1:compY-1;let flat=[];for(const item of transcript()){textLines(item.text,Math.max(10,Math.min(88,chatW-2))).forEach(t=>flat.push({text:t,role:item.role}));for(let i=0;i<item.gap;i++)flat.push({text:'',role:'primary'})}const viewH=maxY-bodyY-1;let offset=historyOffset;if((expanded||s===17)&&flat.length>viewH)offset=Math.min(offset,flat.length-viewH);else offset=Math.min(offset,Math.max(0,flat.length-viewH));if(s===10&&flat.length>viewH)offset=flat.findIndex(l=>l.text.startsWith('[|]'));flat.slice(offset,offset+viewH).forEach((l,i)=>{const yy=bodyY+2+i;put(chatX+1,yy,l.text,['success','error','warning'].includes(l.role)?'primary':l.role);const m=l.text.match(/^\[(>|!|x|\||\?|-)\]/);if(m)put(chatX+1,yy,m[0],m[1]==='>'?'active':m[1]==='!'?'error':m[1]==='|'||m[1]==='?'?'warning':l.role==='success'?'success':'secondary')});if(flat.length>viewH)put(chatX+chatW-1,maxY,offset+viewH<flat.length?'v':'^','muted');
 if(live){const msg=s===4?'[>] Working':s===7?'[>] Running unittest · 12s':s===9?'[>] Exploring repository · 3m 02s':s===8?'[>] Reading tests · 18s':s===11?'[>] Continuing after exit 1':s===14?'[>] Writing answer · 42s':'[>] Thinking · 1s';put(chatX+1,liveY,msg.slice(0,chatW-2),'active')}
 title(chatX,compY,chatW,s===10?'Composer · paused':'Composer',actualOwner==='Composer');fill(chatX,compY+1,chatW,inputH);put(chatX+1,compY+1,(s===10?'Waiting for approval':s===1?'Describe a task…':'Reply, or describe the next task…').slice(0,chatW-2),'muted','panel');if(actualOwner==='Composer')put(chatX+1,compY+1,' ','caret');
 if(term){const y=bottom+1;title(1,y,cols-2,'Terminal',actualOwner==='Terminal');['astra-fixture % python3 -m unittest -v','test_full_name ... ok','test_blank_first_name ... ok','test_blank_last_name ... ok','test_strips_surrounding_spaces ... ok','Ran 4 tests in 0.001s','OK','astra-fixture %'].slice(0,terminalH-1).forEach((v,i)=>put(2,y+1+i,v));}
 fill(0,rows-1,cols,1,'root');let footer='OpenAI/gpt-5.6-luna · Medium';put(1,rows-1,(actualOwner==='Footer'?'> ':'')+footer,actualOwner==='Footer'?'focus':'secondary','root');const meta=s===1?'context 1% · 0 tokens':'context 2% · 101.1k tokens';if(cols>95)put(cols-meta.length-1,rows-1,meta,'muted','root');else put(cols-13,rows-1,'context 2%','muted','root');if(actualOwner==='Modal'||actualOwner==='Approval')fill(0,rows-1,cols,1,'root');
 if(modal)drawModal(modal,chatX,chatW,bottom);
 let html='';for(const row of grid){html+='<div class="row">';let cl='',buf='';for(const c of row){if(c.cl!==cl){if(buf)html+=`<span class="${cl}">${esc(buf)}</span>`;cl=c.cl;buf=c.ch}else buf+=c.ch}if(buf)html+=`<span class="${cl}">${esc(buf)}</span>`;html+='</div>'}terminal.innerHTML=html;terminal.style.width=`${cols}ch`;terminal.dataset.cols=cols;terminal.dataset.rows=rows;terminal.dataset.state=s;selector.value=state;document.querySelector('#state-title').textContent=`${String(s).padStart(2,'0')} / ${scenarios[state][0]}`;document.querySelector('#state-note').textContent=scenarios[state][1];document.querySelector('#geometry').textContent=`${cols}×${rows} cells · Files ${files} · Workspace ${workW} · Conversation ${chatW} · Owner ${actualOwner} · ↑/↓ or PageUp/PageDown scroll transcript in this study. No backend is connected.`;
}
function drawModal(kind,chatX,chatW,bottom){
 if(kind==='theme'){const h=Math.min(12,rows-4),w=Math.min(84,cols-4),x=Math.min(chatX,cols-w-2),y=rows-h-1;box(x,y,w,h,'Theme');['System','Forge Dark','Forge Light'].forEach((v,i)=>put(x+3,y+2+i,`${i===modalChoice?'>':' '} ${v}${i===1?' · current':''}`,i===modalChoice?'focus':'primary','panel'));put(x+3,y+h-2,'↑↓ preview · Enter apply · Esc cancel','secondary','panel');if(rows>=30){const py=Math.max(3,y-7);box(x,py,w,6,'Preview');put(x+3,py+2,'[>] Working  [x] Passed  [?] Waiting  [!] Failed','secondary','panel');put(x+3,py+3,'> Composer  ·  Reference: formatter.py','info','panel')}return}
 const w=Math.min(kind==='save'?64:84,cols-4);const h=kind==='save'?9:kind==='help'?15:Math.min(19,rows-4);const x=Math.floor((cols-w)/2),y=Math.floor((rows-h)/2);box(x,y,w,h,kind==='model'?'Select a model':kind==='save'?'Unsaved changes':kind==='help'?'Help':kind==='provider'?'Select a provider':'Commands');
 if(kind==='save'){put(x+3,y+2,'formatter.py has unsaved changes.','primary','panel');put(x+3,y+4,'Save and leave?','primary','panel');put(x+3,y+6,'Enter/s save · d discard · Esc cancel','secondary','panel');return}
 if(kind==='help'){['Active block: '+owner,'','Tab / Shift+Tab  Move between visible blocks','F4               Model picker','F1               Help','Ctrl+O           Tool details','Esc              Leave one interaction level','','Existing bindings only.'].forEach((v,i)=>put(x+3,y+2+i,v.slice(0,w-6),'secondary','panel'));return}
 put(x+3,y+2,'Filter models…','muted','panel');if(kind==='model'){const nameW=w-45;put(x+3,y+4,'MODEL'.padEnd(nameW)+'  PROVIDER'.padEnd(22)+'  SOURCE / ACCOUNT','secondary','panel');const entries=[['gpt-5.6-luna','OpenAI · ChatGPT','current'],['gpt-5.6-luna','OpenCode · Go','cloud'],['gpt-5.6-luna','OpenCode · Zen','cloud'],['gpt-5.6-sol','OpenAI · ChatGPT','cloud'],['gpt-6-astra','OpenAI · ChatGPT','cloud']];entries.forEach((e,i)=>{const yy=y+6+i;fill(x+1,yy,w-2,1,i===modalChoice?'selected':'panel');put(x+2,yy,i===modalChoice?'>':' ',i===modalChoice?'focus':'secondary',i===modalChoice?'selected':'panel');put(x+4,yy,e[0].padEnd(nameW-1)+'  '+e[1].padEnd(20)+'  '+e[2],'primary',i===modalChoice?'selected':'panel')});textLines('Active: OpenAI · ChatGPT / openai-codex/gpt-5.6-luna / Medium',w-6).forEach((v,i)=>put(x+3,y+h-5+i,v,'secondary','panel'));put(x+3,y+h-2,'↑↓ move · ←→ section · Enter select · Esc close','secondary','panel')}
}
function choose(n){state=(n+30)%30;overlay='';expanded=state===16;historyOffset=0;modalChoice=1;owner=state===9?'Approval':[18,19,20].includes(state)?'Editor':state===21?'Terminal':state===22?'Search':'Composer';if(state===27)setSize(80,24);if(state===28)setSize(120,35);if(state===29)setSize(160,45);render();history.replaceState(null,'',`?state=${state+1}`)}
function setSize(c,r){cols=c;rows=r;document.querySelector('#size').value=`${c},${r}`}
selector.onchange=()=>choose(Number(selector.value));document.querySelector('#size').onchange=e=>{const [c,r]=e.target.value.split(',').map(Number);setSize(c,r);render()};document.querySelector('#palette').onchange=e=>{document.body.classList.toggle('light',e.target.value==='light');render()};document.querySelector('#previous').onclick=()=>choose(state-1);document.querySelector('#next').onclick=()=>choose(state+1);document.querySelector('#details').onclick=()=>{expanded=!expanded;historyOffset=0;render()};
terminal.addEventListener('keydown',e=>{const s=state+1;let handled=true;if(e.ctrlKey&&e.key.toLowerCase()==='o'){expanded=!expanded;historyOffset=0}else if(e.key==='F4'){overlay='model';modalChoice=0}else if(e.key==='F1')overlay='help';else if(e.key==='Escape'){if(overlay)overlay='';else if([24,25,27].includes(s))choose(14);else if(s===20)choose(18);else owner='Composer'}else if((overlay||[24,25].includes(s))&&['ArrowDown','ArrowUp'].includes(e.key)){modalChoice=(modalChoice+(e.key==='ArrowDown'?1:4))%5;if(s===25){modalChoice%=3;document.body.classList.toggle('light',modalChoice===2)}}else if(e.key==='Enter'&&(overlay||[24,25,27].includes(s))){overlay='';if([24,25,27].includes(s))choose(14)}else if(e.key==='Tab'){const list=[...(cols>=116?['Search','Files']:[]),...([2,19,20,21,26,28,29,30].includes(s)?['Editor']:[]),'Conversation','Composer','Footer',...(s===22?['Terminal']:[])];owner=list[(list.indexOf(owner)+(e.shiftKey?-1:1)+list.length)%list.length]}else if(e.key==='i'&&s===19)choose(19);else if(e.key==='ArrowDown')historyOffset++;else if(e.key==='ArrowUp')historyOffset=Math.max(0,historyOffset-1);else if(e.key==='PageDown')historyOffset+=8;else if(e.key==='PageUp')historyOffset=Math.max(0,historyOffset-8);else if(s===23&&e.key==='Backspace')search=search.slice(0,-1);else if(s===23&&e.key.length===1)search+=e.key;else handled=false;if(handled){e.preventDefault();render()}});
choose(state);
